### PR TITLE
"Max stack exceed" error fix

### PR DESCRIPTION
**Pull request by CodeTrol**
I've just changed this line and "max stack size exceed" error is no longer reproducing in the code. I also tested code from [https://github.com/maxtaco/tamejs/issues/39](https://github.com/maxtaco/tamejs/issues/39). I hope I did not break anything else.

### CODE REVIEW

**Comment by sixcircuit** [comment]
Can you run a performance test on that? My thought is it's probably going
to be an order of magnitude slower.

**Comment by maxtaco** [comment]
In iced we return to the main loop every ~100 or so ticks.  @sktaylor I think you're right it might be quite slow

**Comment by CodeTrol** [comment]
well, we can redesign this. I mean not to call process.nextTick every
time... so, it will work faster...

2016-02-13 3:47 GMT+02:00 Maxwell Krohn notifications@github.com:

**Comment by CodeTrol** [comment]
for example like this:

``` js
function callChain (l) {
    if (l.length) {
    var first = l.shift ();
    first (function () {
      callChain.counter = (callChain.counter|0)+1;
      if(callChain.counter > 1000) { // adjust this constant
        callChain.counter = 0;
        process.nextTick(function(){ callChain (l); });
      }
      else callChain(l);
     });
    }
};
```

2016-02-13 19:33 GMT+02:00 Victor Palyvoda 0x80000000h@gmail.com:

**Comment by sixcircuit** [comment]
Sorry for the delay. Is this only a problem if you're using defer in a
synchronous loop?

**Comment by CodeTrol** [comment]
Sorry for late reply. I have not checked that, so I can't give you an answer to your question. But I found that this "fix" will eat too much memory in simple code:

``` js
for(var i = 0; i < 500000; i++) {
    await {
        setTimeout(defer(), 1);
    }
    i % 100 == 0 && console.log(i);
}
```

. So I decided to close this pull request.

**Comment by sixcircuit** [comment]
Thanks for contributing though, always happy to look over anything you
submit.

**Pull request closed without merging**
